openapi: 3.2.0
info:
  title: Datarails Finance OS MCP Server Ready API
  version: 3.0.0
tags:
- name: Ready
paths:
  /ready:
    get:
      summary: Ready
      operationId: ready_ready_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Ready
