openapi: 3.2.0
info:
  title: Datarails Finance OS MCP Server Health API
  version: 3.0.0
tags:
- name: Health
paths:
  /health:
    get:
      summary: Health
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Health
